# Generated by Django 5.2.6 on 2025-12-07 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('form_controls', 'Form Controls'), ('navigation', 'Navigation'), ('media_interaction', 'Media & Interaction'), ('typography', 'Typography'), ('layout', 'Layout'), ('feedback_indicators', 'Feedback & Indicators'), ('styling_theming', 'Styling & Theming')], max_length=50, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('autocomplete', 'Autocomplete'), ('checkbox', 'Checkbox'), ('input', 'Input'), ('radio', 'Radio'), ('range', 'Range'), ('slider', 'Slider'), ('formfield', 'Formfield'), ('button', 'Button'), ('menu', 'Menu'), ('tap', 'Tap'), ('drag_and_drop', 'Drag and Drop'), ('text_component', 'Text Component'), ('expansion_panel', 'Expansion-Panel'), ('grid', 'Grid'), ('scrollbar', 'Scrollbar'), ('dialog', 'Dialog'), ('tooltip', 'Tooltip'), ('progress', 'Progress'), ('snackbar', 'Snackbar'), ('badge', 'Badge'), ('confetti', 'Confetti')], max_length=50, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='meta_components_app.component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'component')},
            },
        ),
    ]
