# Generated by Django 5.2.6 on 2025-12-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_components_app', '0002_componentsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
