# Generated by Django 5.2.6 on 2025-12-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
