# Generated by Django 5.2.6 on 2026-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lemon_order_portal_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
