# Generated by Django 5.2.6 on 2026-02-11 12:46

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_customuser_lemon_order_portal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=auth_app.models.user_profile_upload_path),
        ),
    ]
